CREATE TABLE IF NOT EXISTS xdev_parser_settings (
	ID		int(11) unsigned NOT NULL AUTO_INCREMENT,
	NAME 		varchar(255) NOT NULL,
	FULL_URL	varchar(255) NOT NULL,
	TIMESTAMP_X	timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	ACTIVE		char(1) COLLATE utf8_unicode_ci NOT NULL DEFAULT "Y",
	SORT		int(11) NOT NULL DEFAULT '500',
	TIME_LIMIT	int(11) NULL,
 	IBLOCK_ID	int(11) NOT NULL REFERENCES b_iblock(ID),

 	SPL_ITEM			varchar(255) NOT NULL,
 	SPL_ITEM_HREF			varchar(255) NOT NULL,
 	SPL_ITEM_NAME			varchar(255) NOT NULL,
 	SPL_ITEM_PREVIEW_TEXT		varchar(255) NOT NULL,
 	SPL_ITEM_PREVIEW_PICTURE	varchar(255) NOT NULL,
 	ITEM_PREVIEW_TEXT_TYPE		char(4) COLLATE utf8_unicode_ci NOT NULL DEFAULT "html",

 	SPD_ITEM			varchar(255) NOT NULL,
 	SPD_ITEM_NAME			varchar(255) NOT NULL,
 	SPD_ITEM_DETAIL_TEXT		varchar(255) NOT NULL,
 	SPD_ITEM_DETAIL_PICTURE		varchar(255) NOT NULL,
 	ITEM_DETAIL_TEXT_TYPE		char(4) COLLATE utf8_unicode_ci NOT NULL DEFAULT "html",

	PRIMARY KEY	(ID)
);
DROP TRIGGER IF EXISTS xdev_parser_settings_add_timestamp;
CREATE TRIGGER xdev_parser_settings_add_timestamp BEFORE INSERT ON xdev_parser_settings FOR EACH ROW SET NEW.TIMESTAMP_X = now();